apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api.yaml
  - voice.yaml
  - workers.yaml
  - automation.yaml
  - web.yaml
commonLabels:
  app.kubernetes.io/part-of: ordy
