"""Alembic environment. Runs migrations as the ``ordy_migrator`` role.

Model metadata is imported so future migrations can be autogenerated; the first
migration builds the schema from this metadata and then layers RLS on top.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from ordy_core.db import Base
from sqlalchemy import create_engine, pool

import ordy_core.models  # noqa: F401  — registers all tables on Base.metadata

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _url() -> str:
    return os.environ.get("DATABASE_MIGRATION_URL") or config.get_main_option("sqlalchemy.url")


def run_migrations_offline() -> None:
    context.configure(
        url=_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_engine(_url(), poolclass=pool.NullPool, future=True)
    with engine.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata, compare_type=True
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
