"""Workflow definition model (doc 04 §6).

A workflow is a *declarative* artifact: typed steps with primary + fallback selectors,
an expected-state assertion after each step, and parameter slots. It is generated by AI
at onboarding, verified by a human, then replayed deterministically — no model in the
execution loop (ADR-011).
"""

from __future__ import annotations

from dataclasses import dataclass, field

# Steps whose op writes into the page — these are the ones that must be checked against
# the never-fill list before execution.
WRITE_OPS = {"fill_form", "select_option"}


@dataclass(slots=True)
class Step:
    op: str  # goto | search_click | select_option | click | fill_form | goto_cart_checkout | confirm_order
    target: str | None = None
    url: str | None = None
    strategy: list[str] = field(default_factory=list)  # ordered selector candidates
    value: str | None = None
    fields: dict[str, str] = field(default_factory=dict)
    expect: str | None = None  # assertion evaluated after the step
    never_fill: list[str] = field(default_factory=list)
    capture: str | None = None  # name to capture into the run result
    requires: str | None = None  # e.g. "platform_confirmed_action"


@dataclass(slots=True)
class WorkflowDefinition:
    workflow_id: str
    action_key: str  # which platform tool this implements
    target_domain: str
    steps: list[Step] = field(default_factory=list)
    version: int = 1

    def parameter_names(self) -> set[str]:
        from ordy_automation.params import slots_in

        names: set[str] = set()
        for step in self.steps:
            for text in [step.url, step.value, *step.strategy, *step.fields.values()]:
                if text:
                    names |= slots_in(text)
        return names


@dataclass(slots=True)
class StepResult:
    index: int
    op: str
    ok: bool
    detail: str = ""
    artifact_key: str | None = None


@dataclass(slots=True)
class RunResult:
    ok: bool
    steps: list[StepResult] = field(default_factory=list)
    captured: dict[str, str] = field(default_factory=dict)
    error_code: str | None = None
    error_message: str | None = None

    @property
    def failed_step(self) -> StepResult | None:
        return next((s for s in self.steps if not s.ok), None)
